// src/routes/manga/[id].tsx
import { createResource } from "solid-js";
import { useParams } from "solid-start";
import { ID } from "~/util/props";

const fetch_chapter_data = async (id: string): Promise<any> => { }

export default function MangaId() {
    const { id } = useParams<ID>();
    const [res, { mutate, refetch }] = createResource(id, fetch_chapter_data, {});

    return (
        <main></main>
    )
}

// src/routes/chapter/[id].tsx
import { useParams } from "solid-start";
import { ID } from "~/util/props";

const fetch_chapter_data = async (id: string): Promise<any> => { }

export default function ChapterId() {
    const { id } = useParams<ID>();
    // const [res, { mutate, refetch }] = createResource(id, fetch_chapter_data, {});

    return (
        <main>
            Being implemented ({id})
        </main>
    )
}
