// src/routes/manga/[id].tsx
import { createResource } from "solid-js";
import { useParams } from "solid-start";
import ChapterCard from "~/components/ChapterCard";
import { ApiObject } from "~/util/bindings/ApiObject";
import { ChapterAttributes } from "~/util/bindings/ChapterAttributes";
import { MangaAttributes } from "~/util/bindings/MangaAttributes";
import { ID } from "~/util/props";
import { fetch_resource } from "~/util/resources";

export default function MangaId() {
    const { id } = useParams<ID>();
    const [info] = createResource(
        () => id,
        async (id: string) =>
            await fetch_resource<ApiObject<MangaAttributes>>(`https://api.mangadex.org/manga/${id}`)
    );
    const [feed] = createResource(
        () => id,
        async (id: string) =>
            await fetch_resource<ApiObject<ChapterAttributes>[]>(`https://api.mangadex.org/manga/${id}/feed?limit=500&translatedLanguage[]=en`)
    );

    return (
        <main>
            {/* {info.loading ? "Loading (Manga info)..." : <pre>{JSON.stringify(info()?.data.attributes.title, null, 2)}</pre>} */}
            {/* {feed.loading ? "Loading (Manga feed)..." : <pre>{JSON.stringify(feed()?.data.map(e => e.id), null, 2)}</pre>} */}
            {
                feed.loading ? "Loading (Manga feed)..." : feed()?.data.map(e => <ChapterCard data={e} />)
            }
        </main>
    )
}

// src/pages/manga/[id].vue
<script setup lang="ts">
import { fetch } from '@tauri-apps/api/http'

// Route params
const { id } = useRoute().params

const {
	data: feed,
	pending,
	error
} = useAsyncData(async () => {
	const url = construct_url(`https://api.mangadex.org/manga/${id}/feed`, [
		['limit', '500'],
		['translatedLanguage[]', 'en'],
		['order[chapter]', 'desc']
	])

	const response = await fetch<any>(url, {
		method: 'GET',
		headers: {
			'User-Agent': await userAgent()
		}
	})
	return response.data
})
</script>

<template>
	<template v-if="!pending">
		<NuxtLink
			class="mb-2 ml-2"
			:to="`/chapter/${chapter.id}`"
			v-for="chapter in feed.data"
		>
			{{ chapter.attributes.title || 'null' }}
			<br />
		</NuxtLink>
		<pre>{{ JSON.stringify(feed, null, 2) }}</pre>
	</template>

	<template v-else-if="pending">
		<p>Loading...</p>
	</template>

	<template v-else-if="error">
		<p>An error occurred</p>
		<pre>{{ error }}</pre>
	</template>
</template>
